steps:
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: [ "test" ]

  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ['package', '-Dmaven.test.skip=true']

  - name: gcr.io/cloud-builders/docker
    args: [ 'build', '-t', 'gcr.io/steam-bee-310608/simulation-service', '--build-arg=JAR_FILE=target/simulationservice-0.0.1-SNAPSHOT.jar', '.' ]

  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=deployment.yaml
      - --location=europe-west2-c
      - --cluster=my-first-cluster-1
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'deployment.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west2-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-first-cluster-1'

images: [ 'gcr.io/steam-bee-310608/simulation-service' ]