apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: service-simulation
  name: service-simulation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-simulation
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: service-simulation
    spec:
      containers:
      - image: gcr.io/steam-bee-310608/simulation-service:latest
        name: energygrid-service-simulation
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: simulation-service
spec:
  selector:
    app: service-simulation
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer